import Mathlib
import UnitDistance.C04_SplittingRamification

set_option linter.style.longLine false

/-!
# Definition A.6: Discriminants and Tower Formula

This file formalizes the key discriminant-related definitions for the unit-distance proof:

1. **Absolute discriminant**: For a number field L, D_L := `NumberField.discr L` ∈ ℤ,
   the determinant of the trace form matrix for any ℤ-basis of 𝓞_L.

2. **Relative discriminant**: For a finite extension M/F of number fields, d_{M/F}
   is the ideal of 𝓞_F generated by discriminants of 𝓞_F-bases of 𝓞_M.
   Concretely, d_{M/F} = N_{M/F}(𝔇_{M/F}) where 𝔇_{M/F} is the different ideal.
   In Mathlib: `Ideal.absNorm (differentIdeal (𝓞 F) (𝓞 M))` = |d_{M/F}|.

3. **Tower formula**: For ℚ ⊆ F ⊆ M,
   |D_M| = |D_F|^[M:F] · N_{F/ℚ}(d_{M/F})
   In Mathlib: `NumberField.natAbs_discr_eq_absNorm_differentIdeal_mul_natAbs_discr_pow`.

4. **Root discriminant**: rd(L) = |D_L|^{1/[L:ℚ]} ∈ ℝ.
   In Mathlib: `NumberField.rootDiscr L`.

5. **Unramified extensions preserve root discriminant**: If M/F is everywhere unramified
   at finite places (d_{M/F} = 𝓞_F), then rd(M) = rd(F).

References: [Neu99, Chapter III], [Mar77, Chapter 4].
-/

namespace UnitDistance.NumberTheory

open NumberField NumberField.InfinitePlace

/-!
## Absolute discriminant

Already available in Mathlib as `NumberField.discr L : ℤ`.
-/

/-- The absolute discriminant of a number field L is `NumberField.discr L : ℤ`.
    Its absolute value |D_L| = (NumberField.discr L).natAbs ∈ ℕ. -/
-- Note: `NumberField.discr` is already in Mathlib; this is just documentation.
theorem absDiscr_pos (L : Type*) [Field L] [NumberField L] :
    0 < (discr L).natAbs := by
  exact Nat.pos_of_ne_zero (by exact_mod_cast discr_ne_zero L ∘ Int.natAbs_eq_zero.mp)

/-!
## Root discriminant

`NumberField.rootDiscr L` is already in Mathlib (Mathlib.NumberTheory.NumberField.Discriminant.Basic):
  `rootDiscr K = |discr K| ^ (finrank ℚ K : ℝ)⁻¹`
-/

/-- The root discriminant of a number field L is rd(L) = |D_L|^{1/[L:ℚ]}.
    This is `NumberField.rootDiscr L` in Mathlib. -/
noncomputable def rootDiscriminant (L : Type*) [Field L] [NumberField L] : ℝ :=
  rootDiscr L

/-!
## Relative discriminant and tower formula

The relative discriminant d_{M/F} is captured via the different ideal.
The tower formula is `NumberField.natAbs_discr_eq_absNorm_differentIdeal_mul_natAbs_discr_pow`.
-/

/-- The tower formula for discriminants (Proposition A.6):
    For a tower of number fields ℚ ⊆ F ⊆ M, the absolute discriminant satisfies
    |D_M| = Ideal.absNorm(d_{M/F}) · |D_F|^[M:F],
    where d_{M/F} = differentIdeal (𝓞 F) (𝓞 M) is the different ideal of M/F.

    This is the Mathlib theorem
    `NumberField.natAbs_discr_eq_absNorm_differentIdeal_mul_natAbs_discr_pow`. -/
theorem discriminant_tower_formula_statement
    (F M : Type*) [Field F] [Field M] [NumberField F] [NumberField M]
    [Algebra F M] [IsScalarTower ℚ F M] :
    (NumberField.discr M).natAbs =
      Ideal.absNorm (differentIdeal (𝓞 F) (𝓞 M)) * (NumberField.discr F).natAbs ^ Module.finrank F M :=
  natAbs_discr_eq_absNorm_differentIdeal_mul_natAbs_discr_pow F (𝓞 F) M (𝓞 M)

/-- If M/F has trivial relative discriminant (d_{M/F} = O_F, i.e., M/F is unramified at
    all finite places), then rd(M) = rd(F). This follows from the tower formula:
    if Ideal.absNorm (differentIdeal (𝓞 F) (𝓞 M)) = 1, then
    (discr M).natAbs = (discr F).natAbs ^ finrank F M,
    so |D_M|^{1/[M:ℚ]} = |D_F|^{1/[F:ℚ]}.

    Note: We do NOT include explicit [Algebra ℚ F] and [Algebra ℚ M] hypotheses because
    [NumberField F] and [NumberField M] already provide them, and having both would
    create a module instance diamond that breaks the proof. -/
theorem rootDiscriminant_preserved_by_unramified
    (F M : Type*) [Field F] [Field M] [NumberField F] [NumberField M]
    [Algebra F M] [IsScalarTower ℚ F M]
    (h : Ideal.absNorm (differentIdeal (𝓞 F) (𝓞 M)) = 1) :
    rootDiscr M = rootDiscr F := by
  -- Step 1: Tower formula gives (discr M).natAbs = (discr F).natAbs ^ finrank F M
  have htower : (discr M).natAbs = (discr F).natAbs ^ Module.finrank F M := by
    have := natAbs_discr_eq_absNorm_differentIdeal_mul_natAbs_discr_pow
        F (RingOfIntegers F) M (RingOfIntegers M)
    rw [h, one_mul] at this; exact this
  -- Step 2: Convert ℤ absolute value to natAbs in ℝ
  have conv : ∀ n : ℤ, |(n : ℝ)| = (n.natAbs : ℝ) := fun n => by
    rw [← Int.cast_abs]; simp [Nat.cast_natAbs]
  simp only [rootDiscr, Int.cast_abs, conv]
  -- Step 3: Rewrite using htower and rearrange rpow
  rw [htower]
  push_cast
  rw [← Real.rpow_natCast ((discr F).natAbs : ℝ), ← Real.rpow_mul (Nat.cast_nonneg _)]
  apply congr_arg
  -- Step 4: Exponent arithmetic: finrank F M * (finrank ℚ M)⁻¹ = (finrank ℚ F)⁻¹
  -- using finrank_mul_finrank ℚ F M : finrank ℚ F * finrank F M = finrank ℚ M
  have hFM_nat : Module.finrank ℚ F * Module.finrank F M = Module.finrank ℚ M :=
    Module.finrank_mul_finrank ℚ F M
  have hFM_real : (Module.finrank ℚ F : ℝ) * (Module.finrank F M : ℝ) =
      Module.finrank ℚ M := by exact_mod_cast hFM_nat
  have hF : (Module.finrank ℚ F : ℝ) ≠ 0 :=
    Nat.cast_ne_zero.mpr (Module.finrank_pos (R := ℚ) (M := F)).ne'
  have hFM' : (Module.finrank F M : ℝ) ≠ 0 :=
    Nat.cast_ne_zero.mpr (Module.finrank_pos (R := F) (M := M)).ne'
  rw [← hFM_real]; field_simp

end UnitDistance.NumberTheory
