import Mathlib

set_option linter.style.longLine false

/-!
# Infrastructure: Pro-p Group Type

This file defines `ProPGroup` as a concrete structure (not an `axiom`), bundling
the data needed for the Golod–Shafarevich and Frattini–Burnside analysis:
- minimal generator rank d(G)
- minimal relation rank r(G)
- infiniteness predicate
- nontriviality predicate

Pro-p groups (profinite groups that are p-groups) are not directly formalized in
Mathlib. Rather than asserting them as axioms, we bundle the abstract data as a
structure so that downstream files can state theorems about `ProPGroup` values
without needing the full topological group theory.

This file is intended to be imported by `C11_ProPGroups` and its dependents
(C12, C13, C23, C24, C25, C26) to replace the `axiom ProPGroup : Type*` approach.

The Golod–Shafarevich criterion (4·r(G) ≤ d(G)² → G infinite) is stated as a
standalone axiom in `STANDARD_AXIOMS.lean`, not as a structural field, per
UNITY.md Invariant 2 (no `<hypothesis> → <goal>` Prop fields in structures).
-/

namespace UnitDistance.ProP

/-- A finitely generated pro-p group, bundled as a structure.
    Pro-p groups are profinite groups that are also p-groups.
    This structure captures the abstract data needed for the Golod–Shafarevich
    analysis: generator rank d(G), relation rank r(G), infiniteness, and
    nontriviality.

    The Golod–Shafarevich criterion (if 4·r(G) ≤ d(G)², then G is infinite) is
    stated as a standalone axiom `golodShafarevich_criterion` in `STANDARD_AXIOMS.lean`,
    not as a structural field, per UNITY.md Invariant 2. -/
structure ProPGroup where
  /-- The minimal generator rank d(G) = dim_{F_p}(G/Φ(G)) -/
  genRank : ℕ
  /-- The minimal relation rank r(G) -/
  relRank : ℕ
  /-- Whether G is infinite -/
  isInfinite : Prop
  /-- Whether G is nontrivial (G ≠ {1}) -/
  isNontrivial : Prop

/-- The predicate expressing that a pro-p group is infinite. -/
def ProPGroup.IsInfinite (G : ProPGroup) : Prop := G.isInfinite

/-- The predicate expressing that a pro-p group is nontrivial. -/
def ProPGroup.IsNontrivial (G : ProPGroup) : Prop := G.isNontrivial

/-- The quotient of a pro-p group G by a closed normal subgroup (represented as
    a ProPGroup N). The quotient retains the same generator rank and relation rank
    as G; in applications, the relation rank is bounded by the Frattini–Burnside
    theorem (r(G/N) ≤ r(G) + k for N normally generated by k elements from Φ(G)). -/
def ProPGroup.quotient (G _N : ProPGroup) : ProPGroup :=
  { genRank    := G.genRank
    relRank    := G.relRank
    isInfinite := G.isInfinite
    isNontrivial := G.isNontrivial }

/-- Notation for the generator rank of a pro-p group. -/
notation "d(" G ")" => ProPGroup.genRank G

/-- Notation for the relation rank of a pro-p group. -/
notation "r(" G ")" => ProPGroup.relRank G

end UnitDistance.ProP
