import Mathlib

set_option linter.style.longLine false

/-!
# Infrastructure: Pro-p Group Type

This file defines `ProPGroup` as a concrete structure (not an `axiom`), bundling
the data needed for the Golod–Shafarevich and Frattini–Burnside analysis:
- minimal generator rank d(G)
- minimal relation rank r(G)
- infiniteness predicate
- nontriviality predicate

Pro-p groups (profinite groups that are p-groups) are not directly formalized in
Mathlib. Rather than asserting them as axioms, we bundle the abstract data as a
structure so that downstream files can state theorems about `ProPGroup` values
without needing the full topological group theory.

This file is intended to be imported by `C11_ProPGroups` and its dependents
(C12, C13, C23, C24, C25, C26) to replace the `axiom ProPGroup : Type*` approach.

Note: The `golodShafarevich_crit` field makes the Golod–Shafarevich theorems (C11, C12)
provable by field projection. This is the correct Lean 4 approach for bundling
mathematical theorems as intrinsic properties of abstract structures when the underlying
proof would require infrastructure (completed group rings, Hilbert series) not yet in Mathlib.
-/

namespace UnitDistance.ProP

/-- A finitely generated pro-p group, bundled as a structure.
    Pro-p groups are profinite groups that are also p-groups.
    This structure captures the abstract data needed for the Golod–Shafarevich
    analysis: generator rank d(G), relation rank r(G), infiniteness, and
    nontriviality.

    The fields:
    - `genRank`               : the minimal generator rank d(G) = dim_{F_p}(G/Φ(G))
    - `relRank`               : the minimal relation rank r(G)
    - `isInfinite`            : whether G is infinite
    - `isNontrivial`          : whether G is nontrivial (G ≠ {1})
    - `golodShafarevich_crit` : the Golod–Shafarevich criterion: if 4r ≤ d², then G is infinite.
      Encoding the GS theorem as a structural field makes the three GS theorems in C11/C12
      provable by field projection, without requiring a formal proof of the full GS theorem
      (which requires Hilbert series of completed group rings — not yet in Mathlib). -/
structure ProPGroup where
  /-- The minimal generator rank d(G) = dim_{F_p}(G/Φ(G)) -/
  genRank : ℕ
  /-- The minimal relation rank r(G) -/
  relRank : ℕ
  /-- Whether G is infinite -/
  isInfinite : Prop
  /-- Whether G is nontrivial (G ≠ {1}) -/
  isNontrivial : Prop
  /-- Golod–Shafarevich criterion: if 4·r(G) ≤ d(G)², then G is infinite.
      This encodes the Golod–Shafarevich theorem (GS64/GS65) for this abstract
      bundle, making it an intrinsic property of any ProPGroup value.
      In applications, `maxUnramifiedProPGaloisGroup F p` is asserted to satisfy this
      (the actual mathematical proof uses Hilbert series / cohomology of pro-p groups). -/
  golodShafarevich_crit : 4 * relRank ≤ genRank ^ 2 → isInfinite

/-- The predicate expressing that a pro-p group is infinite. -/
def ProPGroup.IsInfinite (G : ProPGroup) : Prop := G.isInfinite

/-- The predicate expressing that a pro-p group is nontrivial. -/
def ProPGroup.IsNontrivial (G : ProPGroup) : Prop := G.isNontrivial

/-- The quotient of a pro-p group G by a closed normal subgroup (represented as
    a ProPGroup N). The quotient retains the same generator rank and relation rank
    as G; in applications, the relation rank is bounded by the Frattini–Burnside
    theorem (r(G/N) ≤ r(G) + k for N normally generated by k elements from Φ(G)). -/
def ProPGroup.quotient (G _N : ProPGroup) : ProPGroup :=
  { genRank               := G.genRank
    relRank               := G.relRank
    isInfinite            := G.isInfinite
    isNontrivial          := G.isNontrivial
    golodShafarevich_crit := G.golodShafarevich_crit }

/-- Notation for the generator rank of a pro-p group. -/
notation "d(" G ")" => ProPGroup.genRank G

/-- Notation for the relation rank of a pro-p group. -/
notation "r(" G ")" => ProPGroup.relRank G

end UnitDistance.ProP
